services:
  redis:
    container_name: 'redis'
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT_NUMBER=6379
    command: /opt/bitnami/scripts/redis/run.sh
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local